language: go

before_install:
  - sudo apt-get install gfortran

install:
  - go get -d -t ./...
  - git submodule update --init
  - (cd $GOPATH/src/github.com/ready-steady/lapack && make install)
  - go test -v ./...

notifications:
  email:
    on_success: never
